# React app
FROM node:18-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
RUN npm ci --loglevel verbose
RUN npm run build
# Сборка nginx
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /app/nginx_conf/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/nginx_conf/certificate.crt /etc/ssl/certificate.crt
COPY --from=build /app/nginx_conf/private.key /etc/ssl/private.key
CMD ["nginx", "-g", "daemon off;"]